apiVersion: v1
kind: ConfigMap
metadata:
    name: worker-config
data:
    MSG_SERVICE_URL: amqp://localhost
    MSG_QUEUES: web.messaging.queue
    CACHE_HOST: 0.0.0.0
    CACHE_PORT: 6379
    DB_USERNAME: 'root'
    DB_DATABASE: 'chatdb'
    DB_HOST: 'mysql'
    DB_DIALECT: 'sequelize'
    DB_STORAGE: 5
    DB_MAXPOOLSIZE: 1


