version: '3.1'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: pass123
        volumes:
          - ./mysql-data:/var/lib/mysql
        ports:
          - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
          - 8088:8080
    cache:
        image: redis:latest
        ports: 
            - "6379:6379"
    messaging:
        image: "rabbitmq:3-management"
        ports: 
            - "5672:5672"
            - "15672:15672"
    # webserver:
    #     build: ./Dockerfile-webserver
    #     container_name: chatapp_web
    #     environment: 
    #         - NODE_PORT=80
    #     ports: 
    #         - "3001:80"
    # worker:
    #     build: ./Dockerfile-worker
    #     container_name: chatapp_worker
    #     environment: 
    #         - NODE_PORT=80
    #     ports: 
    #         - "3001:80"