version: "3.3"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: pass123
        volumes:
          - ./mysql-data:/var/lib/mysql
        ports:
          - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
          - 8088:8080
    cache:
        image: redis:latest
        ports: 
            - "6379:6379"
    messaging:
        image: "rabbitmq:3-management"
        ports: 
            - "5672:5672"
            - "15672:15672"
    webapi:
        image: chatappweb:latest
        build: 
          context: ../
          dockerfile: Dockerfile-web
        ports: 
          - "3000:80"
          - "9229:9229"
        environment: 
          NODE_ENV: production
          NODE_PORT: 80
          DB_HOST: db
          MSG_SERVICE_URL: amqp://messaging
          MSG_QUEUES: web.messaging.queue
          CACHE_HOST: cache
          CACHE_PORT: 6379
          JWT_SECRETKEY: secretkey1
          JWT_ISSUER: chatapp.auth.server
          JWT_AUDIENCE: chatusers
        restart: always
        depends_on: 
          - db
          - cache
          - messaging
    # webserver:
    #     build: 
    #       context: ../
    #       dockerfile: Dockerfile-web
    #     container_name: chatapp_web
    #     environment: 
    #         - NODE_PORT=80
    #     ports: 
    #         - "3001:80"
    # worker:
    #     build: ./Dockerfile-worker
    #     container_name: chatapp_worker
    #     environment: 
    #         - NODE_PORT=80
    #     ports: 
    #         - "3001:80"