module.exports.cachingconfig = require('./caching.config')
module.exports.messagequeueconfig = require('./messagequeue.config')
module.exports.jwtauth = require('./jwtauth.config')
module.exports.db = require('./db.config')
module.exports.logging = require('./logging.config')